-- SYSTEM
CREATE USER SPRINGBOOTBOARD IDENTIFIED BY SPRINGBOOTBOARD;
GRANT CONNECT, RESOURCE TO SPRINGBOOTBOARD;

INSERT INTO MEMBER VALUES('HONG','홍길동','HONG','NORMAL');
INSERT INTO MEMBER VALUES('KANG','강감찬','KANG','ROLE_ADMIN');
COMMIT;

SELECT * FROM MEMBER;

SELECT * FROM BOARD;